Inference Pipeline
NKI-AI/ahcore pull request #26
Opened 2023-10-05 14:57 UTC by EricMarcus-ai

Implements pipeline for inference;
* Working H5 and TiffWriter callbacks
* Inference callback configs
* "New" WSIBatchSampler for Predict -- needed for lightning pipeline

Questions:
* In utils/manifest.py I had to deal with masks/annotations being None (if not filled in the database). There may be a better /neater way of dealing with this. Any ideas?

2023-10-05 20:03 UTC, jonasteuwen commented on ahcore/utils/manifest.py
> +        _annotations = None
I think the parsing is correct, but can't you change parse_annotations_from_record instead?

2023-10-05 20:04 UTC, jonasteuwen requested changes
Small changes when checking for annotations.

2023-10-06 09:59 UTC, EricMarcus-ai commented on ahcore/utils/manifest.py
> +        _annotations = None
fixed.

2023-10-06 10:42 UTC, jonasteuwen approved these changes
LGTM

2023-10-06 10:52 UTC, merged